all: seq1 seq2 seq3

seq1: step1.c
	gcc -o seq1 step1.c -std=gnu99 -Wall -Werror -pedantic

seq2: step2.c
	gcc -o seq2 step2.c -std=gnu99 -Wall -Werror -pedantic

seq3: step3.c
	gcc -o seq3 step3.c -std=gnu99 -Wall -Werror -pedantic

